name: generate_form
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  schema_form:
#      path: ../
    path: C:/Users/windo/Documents/Flutter/schema_form

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  schema_widget: #^0.1.8
    path: C:/Users/windo/Documents/Flutter/schema_widget
  logging: ^0.11.4
  json_schema: ^2.2.1
  equatable: ^1.1.1
  intl: any
#  flutter_spinkit: ^4.1.1+1
#  google_maps_flutter: ^0.5.21+17
#  flutter_localizations:
#    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/testUberHomeSchema.json
    - assets/testUberWaitSchema.json
    - assets/testAppLayoutSchema.json
    - assets/testLayoutSchema.json
    - assets/testDataSchema.json
    - assets/testDataValue.json
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
