name: generate_form
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  schema_form:
    path: ..
  schema_widget: ^1.0.0-5
  logging: ^0.11.4
  json_schema: ^2.2.1
  intl: ^0.16.1
  http: ^0.12.2
  provider: ^4.3.2+1
  flutter_form_builder: #^3.14.0-alpha.1
    git:
      url: git://github.com/ryanhz/flutter_form_builder.git
      ref: master
# flutter_chips_input: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

flutter:
  uses-material-design: true
