policies:
  - type: commit
    spec:
      header:
        length: 50
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - "build"
          - "chore"
          - "ci"
          - "docs"
          - "feat"
          - "fix"
          - "perf"
          - "refactor"
          - "revert"
          - "style"
          - "test"
        scopes:
          - "lefthook"
          - "release"
          - "license"
        descriptionLength: 72
  - type: license
    spec:
      skipPaths:
        - .git/
        - .build*/
      includeSuffixes:
        - .ext
      excludeSuffixes:
        - .exclude-ext-prefix.ext
      header: |
        This is the contents of a license header.
