include: package:effective_dart/analysis_options.yaml
#include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  exclude:
    - examples/**
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
