name: schema_form
description: "Schema_form is a Flutter package based on two other packages that produces forms dynamically interpreting JSON objects:

* [dynamic_widget](https://pub.dev/packages/dynamic_widget) - Which builds forms through JSON interpretation;
* [json_schema](https://pub.dev/packages/json_schema) - Identifying, defining and validating the properties of the object being edited."
version: 1.0.0
author: Alex Manoel Ferreira Silva <alex@legytma.com.br>
homepage: https://github.com/Legytma/schema_form

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.5
  rxdart: ^0.22.6
#  json_schema:
#    git:
#      url: https://github.com/Legytma/json_schema.git
#      ref: 2.2.2
  json_schema: ^2.2.1
#  flutter_bloc_extensions: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  dynamic_widget: ^1.0.5
  meta: ">=1.1.7 <2.0.0"
  bloc: ^2.0.0
  intl: ">=0.14.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.1.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
