name: schema_form
description: "Schema_form is a Flutter package based on two other packages that produces forms dynamically interpreting JSON objects."
version: 2.0.0-alpha+1
author: Alex Manoel Ferreira Silva <alex@legytma.com.br>
homepage: https://github.com/Legytma/schema_form

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.5
  rxdart: ">=0.22.0 <1.0.0"
#  json_schema:
#    git:
#      url: https://github.com/Legytma/json_schema.git
#      ref: 2.2.2
  json_schema: ^2.2.1
#  flutter_bloc_extensions: ^0.1.2
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  schema_widget: ^0.1.2
  meta: ">=1.1.7 <2.0.0"
  bloc: ^3.0.0
  intl: ">=0.14.0 <1.0.0"
  logging: ^0.11.4
  google_maps_flutter: ^0.5.24+1
  enum_to_string: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
