name: schema_form
description: A flutter plugin to use convert Json schema to Form Basic
version: 0.0.3
author: Alex Manoel Ferreira Silva <windolboy@gmail.com>
homepage: https://github.com/Legytma/schema_form

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.0
  rxdart: ^0.22.5
#  json_schema:
#    git:
#      url: https://github.com/Legytma/json_schema.git
#      ref: 2.2.2
  json_schema: ^2.2.1
#  flutter_bloc_extensions: ^0.1.2
  equatable: ^0.6.1
  flutter_bloc: ^1.0.0
  dynamic_widget: ^1.0.5
  meta: ">=1.1.7 <1.1.9"
  bloc: ^1.0.0
  intl: ">=0.15.0 <0.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
