name: schema_form
description: "Schema_form is a Flutter package based on two other packages that
  produces forms dynamically interpreting JSON objects."
version: 2.0.0-alpha+1
homepage: https://github.com/Legytma/schema_form

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1
  json_schema: ^2.2.1
  intl: ^0.16.1
  logging: ^0.11.4
  provider: ^4.3.2+1
  flutter_form_builder: #^3.14.0-alpha.1
    git:
      url: git://github.com/ryanhz/flutter_form_builder.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.4

flutter:
  uses-material-design: true
